### ISSUE TITLE
Missing js/build/static/css/main.e284d373.css in libraries.yml

### ISSUE THREAD

**Issue by mglaman** [mspae/commerce_admin_order_advanced#6]
It looks like post-build.js needs to be updated to generate the CSS file into libraries.yml

**Comment by mspae** [comment]
Will look into this today.

**Comment by mspae** [comment]
With https://github.com/mspae/commerce_admin_order_advanced/pull/7 merged there is no longer a CSS file in this module. This is added by the core module.
